import { LOCALIZATION_KEY_AUTHENTICATE, LOCALIZATION_KEY_AUTHENTICATION_REQUIRED, LOCALIZATION_KEY_SWITCH_TO_OFFLINE_MODE } from "./LOCALIZATION_KEY.mjs";

export const TEXTS_DE = Object.freeze({
    [LOCALIZATION_KEY_AUTHENTICATE]: "Authentisieren",
    [LOCALIZATION_KEY_AUTHENTICATION_REQUIRED]: "Authentisierung erforderlich",
    [LOCALIZATION_KEY_SWITCH_TO_OFFLINE_MODE]: "In den Offline-Modus wechseln"
});
